/* --- FILE: /valuation/vb-methods.js ---
   Thư viện PHƯƠNG PHÁP của Valuation Bench: mỗi phương pháp định giá, chỉ báo cơ bản, chỉ báo kỹ thuật và bước tổng hợp có định nghĩa, công thức, khi nào dùng, giới hạn và cách đọc kết quả.
   Nội dung tĩnh (không gọi API). Nạp bằng thẻ <script> thường (global VBMethods) và module.exports cho Vitest (kiểm tra mỗi phương pháp đủ trường). */
const VBMethods = (function () {
  const GROUPS = {
    intrinsic: 'Giá trị nội tại (dòng tiền)', relative: 'So sánh bội số', asset: 'Tài sản, thu nhập và cổ tức', fundamental: 'Phân tích cơ bản và chất lượng',
    technical: 'Phân tích kỹ thuật', market: 'Bối cảnh thị trường', synth: 'Tổng hợp và độ tin cậy',
  };
  const M = (id, group, name, what, formula, use, limit, read) => ({ id: id, group: group, name: name, what: what, formula: formula, use: use, limit: limit, read: read });

  const LIST = [
    // ---------- giá trị nội tại ----------
    M('dcf', 'intrinsic', 'DCF dòng tiền doanh nghiệp (FCFF)',
      'Giá trị doanh nghiệp là hiện giá của dòng tiền tự do mà doanh nghiệp tạo ra cho MỌI nhà cung cấp vốn (cổ đông và chủ nợ), chiết khấu theo chi phí vốn bình quân (WACC); sau đó trừ nợ, cộng tiền, trừ cổ đông thiểu số để ra giá trị vốn chủ.',
      'FCFF = EBIT × (1 − thuế) − tái đầu tư\nTái đầu tư = Δ doanh thu / (doanh thu ÷ vốn đầu tư)\nEV = Σ FCFFₜ / (1+WACC)ᵗ + Giá trị cuối kỳ / (1+WACC)ᴺ\nGiá trị cuối kỳ = NOPAT × (1+g) × (1 − g/ROIC) / (WACC − g)',
      'Doanh nghiệp phi tài chính có lợi nhuận và dòng tiền dự phóng được, tăng trưởng không quá nhảy vọt. Là phương pháp có trọng số cao nhất của bộ công cụ.',
      'Giá trị cuối kỳ thường chiếm 60-80% EV nên rất nhạy với WACC và tăng trưởng dài hạn (lệch 1 điểm % có thể đổi giá trị hàng chục %). Không dùng cho ngân hàng, chứng khoán, bảo hiểm vì nợ là nguyên liệu kinh doanh. Cổ đông thiểu số được trừ theo tỷ lệ lợi nhuận họ hưởng, không theo giá sổ sách.',
      'Đọc cùng bảng nhạy cảm WACC × g và Monte Carlo, không đọc một con số. Nếu giá trị cuối kỳ chiếm quá 75% EV, kết quả chủ yếu là giả định về tương lai xa.'),
    M('fcfe', 'intrinsic', 'FCFE nhiều giai đoạn',
      'Chiết khấu dòng tiền thuộc về cổ đông bằng chi phí vốn chủ (Ke). EPS tăng ở tốc độ g₁ trong N năm rồi giảm dần; dòng tiền cho cổ đông = EPS × (1 − g/ROE), tức tái đầu tư vừa đủ để đạt tăng trưởng đó.',
      'FCFEₜ = EPSₜ × (1 − gₜ / ROE)\nGiá trị = Σ FCFEₜ / (1+Ke)ᵗ + Giá trị cuối kỳ Gordon',
      'Ngân hàng, chứng khoán, bảo hiểm và doanh nghiệp nợ ổn định, nơi khó tách dòng tiền hoạt động khỏi hoạt động tài trợ.',
      'Phụ thuộc vào ROE bền vững và tỷ lệ tái đầu tư; ROE cao bất thường làm giá trị phình ra.',
      'So với P/B hợp lý và thu nhập thặng dư: ba phương pháp cùng dựa trên ROE và Ke nên thường cho kết quả gần nhau; nếu lệch nhiều, kiểm tra ROE và g.'),
    M('ri', 'intrinsic', 'Thu nhập thặng dư (Residual Income)',
      'Giá trị cổ phần = giá trị sổ sách hiện tại + hiện giá phần lợi nhuận VƯỢT chi phí vốn chủ trong tương lai. Doanh nghiệp chỉ tạo giá trị khi ROE lớn hơn Ke.',
      'Giá trị = BVPS₀ + Σ (ROEₜ − Ke) × BVPSₜ₋₁ / (1+Ke)ᵗ + giá trị cuối kỳ\nROE trôi tuyến tính về mức dài hạn; sổ sách tăng nhờ lợi nhuận giữ lại',
      'Ngân hàng và doanh nghiệp có vốn chủ làm nền tảng (chứng khoán, bảo hiểm). Neo giá trị vào sổ sách nên ít nhạy với giả định xa hơn DCF.',
      'Chất lượng của sổ sách quyết định kết quả (nợ xấu chưa trích lập làm vốn chủ ảo); giả định ROE về Ke là thận trọng với doanh nghiệp có lợi thế cạnh tranh bền.',
      'Nếu giá thị trường thấp hơn BVPS mà ROE vẫn trên Ke, thị trường đang nghi ngờ chất lượng tài sản; kiểm tra tỷ lệ nợ xấu và bao nợ xấu.'),
    M('justified-pb', 'intrinsic', 'P/B hợp lý = (ROE − g) / (Ke − g)',
      'Biến thể rút gọn của thu nhập thặng dư khi ROE và g ổn định: P/B càng cao khi ROE vượt Ke càng nhiều.',
      'P/B hợp lý = (ROE − g) / (Ke − g)\nGiá hợp lý = P/B hợp lý × BVPS',
      'Nhanh để kiểm tra một P/B có "đáng" hay không với ngân hàng và tài chính.',
      'Rất nhạy khi Ke gần g (mẫu số nhỏ); giả định ROE vĩnh viễn.',
      'P/B thị trường cao hơn P/B hợp lý nghĩa là giá đang hàm ý ROE cao hơn hoặc tăng trưởng nhanh hơn giả định.'),
    M('ddm', 'asset', 'Mô hình cổ tức (Gordon, hai giai đoạn, H-model)',
      'Giá trị cổ phần là hiện giá cổ tức tương lai. Gordon: cổ tức tăng đều vĩnh viễn; hai giai đoạn: tăng nhanh rồi chậm; H-model: tốc độ tăng giảm tuyến tính.',
      'Gordon: P = D₀ (1+g) / (Ke − g)\nHai giai đoạn: Σ D₀(1+g₁)ᵗ/(1+Ke)ᵗ + P_N/(1+Ke)ᴺ',
      'Doanh nghiệp trả cổ tức đều và có tỷ lệ chi trả ổn định (điện, nước, tiêu dùng thiết yếu, ngân hàng trả tiền mặt).',
      'Doanh nghiệp giữ lại lợi nhuận để tăng trưởng (cổ tức thấp) sẽ bị định giá thấp quá mức; cổ tức bằng cổ phiếu không phải dòng tiền.',
      'Trọng số mặc định thấp; chỉ nên tin khi tỷ lệ chi trả cổ tức tiền mặt từ 40% lợi nhuận trở lên.'),
    M('reverse-dcf', 'intrinsic', 'DCF ngược (điều gì phải đúng)',
      'Thay vì hỏi "giá trị là bao nhiêu", hỏi "giá hiện tại ngầm định thị trường kỳ vọng gì": tìm tăng trưởng, WACC hoặc biên lợi nhuận làm DCF khớp đúng giá thị trường.',
      'Giải f(x) = giá thị trường bằng chia đôi khoảng trên tăng trưởng giai đoạn đầu, WACC hoặc biên EBIT',
      'Kiểm tra tính hợp lý của giá: thị trường có đang đòi hỏi tăng trưởng vô lý (cổ phiếu đắt) hoặc bi quan quá mức (cổ phiếu rẻ) so với lịch sử không.',
      'Các biến khác giữ nguyên nên chỉ là một lát cắt của không gian giả định.',
      'So tăng trưởng ngầm định với CAGR doanh thu 3 năm: ngầm định cao hơn nhiều là kỳ vọng lớn, thấp hơn nhiều là thị trường đã định giá sự suy giảm.'),
    M('monte-carlo', 'intrinsic', 'Mô phỏng Monte Carlo',
      'Chạy DCF hàng nghìn lần, mỗi lần rút ngẫu nhiên tăng trưởng, biên, WACC, tăng trưởng dài hạn và hiệu quả vốn quanh giả định cơ sở (phân phối tam giác, hạt giống cố định nên tái lập được), rồi xem phân phối giá trị.',
      'N lần: draw ~ Tam giác(−a, 0, +a); giá trị = DCF(draw); báo phân vị 5-95%, xác suất giá trị > giá',
      'Cho thấy độ bất định của giả định bằng một dải thay vì một con số và xác suất giá trị vượt giá hiện tại (theo mô hình).',
      'Các biến rút độc lập (không mô phỏng tương quan), và độ rộng do chính người dùng chọn: đây là độ bất định của GIẢ ĐỊNH, không phải xác suất thật của thị trường.',
      'Dải p5-p95 hẹp không có nghĩa là chắc chắn; xem phần giá trị cuối kỳ có chiếm tỷ trọng quá lớn không.'),
    M('scenarios', 'intrinsic', 'Kịch bản bi quan / cơ sở / lạc quan',
      'Ba bộ giả định có xác suất (25% / 50% / 25%) dịch chuyển tăng trưởng, biên và WACC; giá trị kỳ vọng là trung bình có trọng số xác suất.',
      'Kỳ vọng = Σ xác suấtᵢ × giá trịᵢ',
      'Cho hội đồng đầu tư một dải rủi ro/kết quả dễ hiểu; dải thấp/cao của DCF trong biểu đồ tổng hợp lấy từ đây.',
      'Xác suất do người dùng gán, không phải đo được.',
      'Khoảng cách giữa bi quan và lạc quan là thước đo mức nhạy của cổ phiếu với giả định.'),

    // ---------- so sánh bội số ----------
    M('peer-multiples', 'relative', 'Bội số ngang hàng (P/E, P/B, P/S, EV/EBITDA, EV/Doanh thu)',
      'Áp bội số của các mã cùng ngành ICB (phân vị 20 / 50 / 80) vào số liệu của chính cổ phiếu để ra khoảng giá. Nhóm cần tối thiểu 5 mã, vốn hoá từ 300 tỷ.',
      'Giá = bội số nhóm × chỉ tiêu của mã (EPS, BVPS, doanh thu/cp)\nEV-based: giá = (bội số × EBITDA − nợ − thiểu số + tiền + liên kết) / số cổ phiếu',
      'Nhanh và gắn với mặt bằng thị trường hiện tại; P/E cho doanh nghiệp lãi ổn định, P/B cho ngân hàng và doanh nghiệp nặng tài sản, EV/EBITDA cho doanh nghiệp nợ nhiều hoặc khác cấu trúc vốn.',
      'Không tính khác biệt tăng trưởng, đòn bẩy, chất lượng; ngành ICB cấp 2 rộng nên "cùng ngành" chưa chắc cùng mô hình kinh doanh. Ngân hàng, bảo hiểm, tài chính chỉ so P/E và P/B.',
      'Ngay cả khi rẻ hơn ngành, hãy xem ROE và tăng trưởng: rẻ vì kém khác với rẻ thật.'),
    M('hist-multiples', 'relative', 'Dải bội số lịch sử của chính cổ phiếu',
      'Phân vị 20 / 50 / 80 của P/E hoặc P/B hằng ngày trong 5 năm của chính mã, áp vào EPS/BVPS hiện tại: giả định doanh nghiệp quay về mức định giá thường thấy.',
      'Giá = P/E (hoặc P/B) lịch sử × EPS (hoặc BVPS) hiện tại',
      'Doanh nghiệp có mô hình kinh doanh ổn định qua chu kỳ.',
      'Sai khi cấu trúc kinh doanh, lãi suất hoặc kỳ vọng tăng trưởng đã đổi; P/E lịch sử bị bóp méo bởi lợi nhuận bất thường.',
      'Phân vị hiện tại của P/E trong lịch sử cho biết cổ phiếu đang rẻ hay đắt so với CHÍNH NÓ (không so với ngành).'),
    M('peg', 'relative', 'PEG và P/E hợp lý của Lynch',
      'PEG = P/E chia tốc độ tăng EPS (%). Lynch coi P/E hợp lý xấp xỉ tăng trưởng (cộng tỷ suất cổ tức): PEG bằng 1 là hợp lý.',
      'P/E hợp lý ≈ g (%) + tỷ suất cổ tức (%)\nGiá = EPS × P/E hợp lý',
      'Cổ phiếu tăng trưởng ổn định, EPS dương.',
      'Tăng trưởng quá khứ không bảo đảm tương lai; kẹp g ở 30% để tránh giá trị phi thực tế. Không hợp doanh nghiệp chu kỳ.',
      'PEG dưới 1 chỉ hấp dẫn khi tăng trưởng có chất lượng (CFO theo kịp lợi nhuận).'),
    M('earnings-yield', 'relative', 'Lợi suất lợi nhuận và phần bù so với trái phiếu',
      'Lợi suất lợi nhuận = 1 / P/E. Trừ lợi suất trái phiếu chính phủ 10 năm ra phần bù cổ phiếu quan sát được (cùng ý với "mô hình Fed"). Âm hoặc thấp: cổ phiếu không còn phần bù so với trái phiếu.',
      'Phần bù = 100 / P/E − lợi suất TPCP 10 năm (điểm %)',
      'Đánh giá mặt bằng thị trường hoặc ngành so với lãi suất phi rủi ro.',
      'Lịch sử lợi suất TPCP của app mới tích luỹ từ 10/2026 nên chưa có chuỗi phần bù theo thời gian.',
      'Phần bù trên 3 điểm % là thoải mái; dưới 0 là cảnh báo mặt bằng đắt so với lãi suất.'),

    // ---------- tài sản, thu nhập, cổ tức ----------
    M('graham', 'asset', 'Số Graham và công thức tăng trưởng của Graham',
      'Số Graham = √(22,5 × EPS × BVPS): giá tối đa cho nhà đầu tư phòng thủ (P/E ≤ 15 và P/B ≤ 1,5). Công thức 1974: V = EPS × (8,5 + 2g) × 4,4 / Y với Y là lợi suất trái phiếu.',
      'Graham = √(22,5 × EPS × BVPS)\nV = EPS × (8,5 + 2g) × 4,4 / Y',
      'Sàng lọc nhanh cổ phiếu giá trị truyền thống.',
      'Thường thấp hơn giá của cổ phiếu tăng trưởng; công thức tăng trưởng phình ra khi lãi suất thấp (Y nhỏ).',
      'Dùng như một hàng rào tham khảo, trọng số thấp.'),
    M('epv', 'asset', 'Giá trị sức sinh lời (EPV) của Greenwald',
      'Giá trị của doanh nghiệp NẾU lợi nhuận hiện tại bền vững và KHÔNG tăng trưởng: lợi nhuận hoạt động chuẩn hoá sau thuế chia WACC, cộng tiền, trừ nợ và thiểu số.',
      'EPV = NOPAT chuẩn hoá / WACC\nGiá trị vốn chủ = EPV + tiền + liên kết − nợ − thiểu số',
      'Neo giá trị vào lợi nhuận thật chứ không vào kỳ vọng tăng trưởng.',
      'Giả định lợi nhuận hiện tại bền; với doanh nghiệp đang ở đáy chu kỳ EPV thấp, ở đỉnh chu kỳ EPV cao.',
      'Giá thị trường cao hơn EPV bao nhiêu chính là phần thị trường trả cho tăng trưởng; nếu giá dưới EPV, thị trường đang định giá sự suy giảm.'),
    M('nav', 'asset', 'Giá trị tài sản ròng điều chỉnh (NAV / RNAV)',
      'Vốn chủ sở hữu công ty mẹ cộng các khoản điều chỉnh nhập tay (đánh giá lại đất, bất động sản đầu tư, trừ tài sản vô hình), chia số cổ phiếu.',
      'NAV/cp = (vốn chủ công ty mẹ + điều chỉnh) / số cổ phiếu',
      'Bất động sản, khu công nghiệp, doanh nghiệp nặng tài sản có giá trị thị trường khác xa sổ sách.',
      'Giá sổ sách là giá gốc lịch sử; điều chỉnh do người dùng nhập, nên chỉ có trong tổng hợp khi bạn nhập điều chỉnh.',
      'So P/NAV: dưới 1 có thể là cơ hội hoặc phản ánh tài sản kém chất lượng.'),
    M('ncav', 'asset', 'NCAV (Graham net-net)',
      'Tài sản lưu động trừ TOÀN BỘ nợ phải trả, chia số cổ phiếu. Giá dưới 2/3 NCAV là vùng "net-net" cổ điển.',
      'NCAV/cp = (tài sản lưu động − tổng nợ) / số cổ phiếu',
      'Tìm cổ phiếu cực rẻ so với tài sản thanh khoản.',
      'Rất hiếm; phải thu và tồn kho có thể thấp hơn sổ sách khi thanh lý; thường là doanh nghiệp gặp khó. Chỉ hiển thị, không tính vào giá trị đồng thuận.',
      'Giá dưới NCAV mà doanh nghiệp vẫn đốt tiền thì không phải cơ hội.'),
    M('sotp', 'asset', 'Tổng các phần (SOTP)',
      'Định giá từng mảng kinh doanh bằng bội số của doanh nghiệp thuần ngành, cộng lại, rồi trừ nợ ròng và áp chiết khấu tập đoàn.',
      'EV = Σ chỉ tiêu mảngᵢ × bội sốᵢ\nVốn chủ = EV + tiền − nợ − thiểu số − chiết khấu tập đoàn',
      'Tập đoàn đa ngành (ví dụ công nghệ + viễn thông + giáo dục).',
      'Bội số từng mảng do người dùng chọn; chiết khấu tập đoàn 10-30% là phán đoán.',
      'Kết quả mạnh nhất khi mỗi mảng có doanh nghiệp niêm yết cùng ngành để đối chiếu.'),

    // ---------- phân tích cơ bản ----------
    M('dupont', 'fundamental', 'Phân rã DuPont',
      'Tách ROE thành các động lực: biên lợi nhuận, vòng quay tài sản, đòn bẩy tài chính (3 bước), thêm gánh nặng thuế và gánh nặng lãi (5 bước).',
      'ROE = Biên ròng × Vòng quay tài sản × Đòn bẩy\n5 bước: Thuế × Lãi × Biên EBIT × Vòng quay × Đòn bẩy',
      'Biết ROE cao nhờ đâu: biên cao (lợi thế cạnh tranh), vòng quay (hiệu quả) hay chỉ nhờ đòn bẩy (rủi ro).',
      'Dùng số bình quân hai đầu kỳ; gánh nặng lãi có thể lớn hơn 1 khi thu nhập tài chính lớn.',
      'ROE cao nhờ đòn bẩy kém bền hơn ROE cao nhờ biên.'),
    M('roic-wacc', 'fundamental', 'ROIC so với WACC',
      'ROIC = NOPAT / tài sản hoạt động ròng bình quân. Doanh nghiệp chỉ tạo giá trị khi ROIC lớn hơn chi phí vốn (WACC).',
      'ROIC = EBIT × (1 − thuế) / (tài sản − tiền − đầu tư tài chính − nợ không lãi)',
      'Đo chất lượng vốn: ROIC bền vững trên WACC là dấu hiệu lợi thế cạnh tranh.',
      'Doanh nghiệp tiền mặt lớn có tài sản hoạt động nhỏ nên ROIC phình; xem cùng biên và vòng quay.',
      'ROIC − WACC là "phần giá trị tạo ra"; kéo dài nhiều năm mới đáng tin.'),
    M('piotroski', 'fundamental', 'Piotroski F-score (9 tiêu chí)',
      'Chín tiêu chí 0/1 về sinh lời (ROA dương, CFO dương, ROA tăng, CFO > lợi nhuận), đòn bẩy-thanh khoản (nợ dài hạn giảm, thanh toán hiện hành tăng, không phát hành cổ phiếu thu tiền) và hiệu quả (biên gộp tăng, vòng quay tài sản tăng).',
      'F = tổng điểm 9 tiêu chí; 8-9 mạnh, 5-7 trung bình, 0-4 yếu (quy đổi theo tỷ lệ khi thiếu dữ liệu)',
      'Sàng lọc xu hướng cải thiện của doanh nghiệp rẻ (mã giá trị có F cao tốt hơn mã F thấp).',
      'Đo SỰ THAY ĐỔI so với năm trước chứ không đo mức tuyệt đối: doanh nghiệp xuất sắc nhưng giảm biên vẫn bị điểm thấp. Cổ phiếu thưởng không bị phạt, chỉ phát hành thu tiền lớn hơn 1% vốn chủ.',
      'Đọc từng tiêu chí chứ không chỉ tổng điểm.'),
    M('altman', 'fundamental', 'Altman Z',
      'Điểm dự báo nguy cơ kiệt quệ tài chính. Z" (không sản xuất / thị trường mới nổi) = 6,56·X1 + 3,26·X2 + 6,72·X3 + 1,05·X4: an toàn > 2,6, nguy cơ < 1,1. Z gốc có thêm vốn hoá và doanh thu.',
      'X1 = (TS ngắn hạn − nợ ngắn hạn)/TS; X2 = LN giữ lại/TS; X3 = EBIT/TS; X4 = vốn chủ/nợ',
      'Soát rủi ro nợ trước khi tin dòng tiền tương lai của DCF.',
      'Hiệu chỉnh trên mẫu doanh nghiệp Mỹ; không dùng cho ngân hàng, chứng khoán, bảo hiểm. Là tín hiệu soát, không phải dự báo vỡ nợ.',
      'Vùng xám (1,1-2,6) cần xem thêm thanh khoản và kỳ hạn nợ.'),
    M('beneish', 'fundamental', 'Beneish M-score (8 biến)',
      'Mô hình thống kê phát hiện khả năng điều chỉnh lợi nhuận từ tám biến (phải thu, biên gộp, chất lượng tài sản, tăng trưởng doanh thu, khấu hao, chi phí quản lý, dồn tích, đòn bẩy).',
      'M = −4,84 + 0,920·DSRI + 0,528·GMI + 0,404·AQI + 0,892·SGI + 0,115·DEPI − 0,172·SGAI + 4,679·TATA − 0,327·LVGI\nM > −1,78: cần soát',
      'Soát chất lượng lợi nhuận trước khi tin các phương pháp dựa trên lợi nhuận.',
      'Hiệu chỉnh trên mẫu Mỹ; doanh nghiệp tăng trưởng rất nhanh cũng có thể bị gắn cờ vì lý do hợp lệ.',
      'Cờ chỉ có nghĩa "đọc kỹ thuyết minh báo cáo", không phải kết luận gian lận.'),
    M('accruals', 'fundamental', 'Chỉ số dồn tích Sloan và chuyển hoá lợi nhuận thành tiền',
      'Dồn tích = (lợi nhuận − CFO) / tài sản bình quân. Dồn tích cao nghĩa là lợi nhuận phần lớn không phải tiền thật; kèm tỷ lệ CFO / lợi nhuận.',
      'Dồn tích = (Lợi nhuận ròng − CFO) / Tài sản bình quân',
      'Phát hiện lợi nhuận "chất lượng thấp" sớm hơn lợi nhuận giảm.',
      'Doanh nghiệp đang mở rộng mạnh (tăng phải thu, tồn kho) tự nhiên có dồn tích dương.',
      'Trên +10% hoặc dưới −10% tài sản là vùng cần soát.'),
    M('wc-cycle', 'fundamental', 'Vòng quay vốn lưu động (DSO, DIO, DPO, CCC)',
      'Số ngày thu tiền, tồn kho và trả tiền nhà cung cấp; chu kỳ chuyển hoá tiền = DSO + DIO − DPO.',
      'DSO = phải thu/doanh thu × 365; DIO = tồn kho/giá vốn × 365; DPO = phải trả/giá vốn × 365',
      'Phát hiện áp lực dòng tiền và quyền thương lượng với nhà cung cấp, khách hàng.',
      'So trong cùng ngành; thời điểm cuối năm có thể bị méo bởi mùa vụ.',
      'CCC kéo dài ra nhiều năm là dấu hiệu tăng trưởng đang tiêu tiền.'),
    M('bank-metrics', 'fundamental', 'Chỉ số ngân hàng',
      'ROE, ROA, NIM xấp xỉ (thu nhập lãi thuần / tài sản bình quân), tỷ lệ chi phí/thu nhập (CIR), chi phí tín dụng, tỷ lệ cho vay/tiền gửi (LDR), tỷ trọng thu nhập ngoài lãi, đòn bẩy, tăng trưởng tín dụng và huy động.',
      'CIR = chi phí hoạt động / tổng thu nhập; chi phí tín dụng = dự phòng / dư nợ bình quân',
      'Ngân hàng, nơi nợ là nguyên liệu: các chỉ tiêu này thay cho ROIC, nợ/vốn.',
      'Nguồn miễn phí không có nợ xấu (NPL), CAR, CASA: cần soát thủ công báo cáo.',
      'ROE cao đi cùng CIR thấp và chi phí tín dụng ổn định bền hơn ROE cao nhờ đòn bẩy.'),
    M('sustainable-growth', 'fundamental', 'Tăng trưởng bền vững và tăng trưởng lịch sử',
      'g bền vững = ROE × tỷ lệ giữ lại lợi nhuận: tốc độ tăng vốn chủ nếu không huy động thêm. Dùng kèm CAGR doanh thu/lợi nhuận 3-5 năm làm điểm xuất phát cho giả định.',
      'g = ROE × (1 − tỷ lệ chi trả cổ tức)',
      'Cơ sở hợp lý cho tăng trưởng giai đoạn đầu của DCF (60% CAGR doanh thu + 40% tăng trưởng bền vững).',
      'Lịch sử không bảo đảm tương lai; doanh nghiệp huy động vốn có thể tăng nhanh hơn g bền vững.',
      'Giả định tăng trưởng lớn hơn nhiều so với g bền vững cần một nguồn vốn rõ ràng.'),

    // ---------- kỹ thuật ----------
    M('trend-ma', 'technical', 'Xu hướng: đường trung bình (SMA/EMA 20, 50, 100, 200)',
      'Giá so với các đường trung bình và thứ tự sắp xếp của chúng mô tả xu hướng ngắn, trung và dài hạn. Giao cắt vàng là SMA50 cắt lên SMA200, giao cắt chết là ngược lại.',
      'SMA(n) = trung bình giá đóng cửa n phiên\nEMA có trọng số lớn hơn cho phiên gần',
      'Xác định xu hướng chính; SMA200 dốc lên và giá trên SMA200 là xu hướng tăng dài hạn.',
      'Đường trung bình luôn trễ; tín hiệu giao cắt thường đến muộn và nhiễu khi giá đi ngang.',
      'Dùng cùng ADX: xu hướng chỉ đáng tin khi ADX từ 20-25 trở lên.'),
    M('adx', 'technical', 'ADX và +DI / −DI',
      'ADX đo SỨC MẠNH xu hướng (không phải hướng); +DI so với −DI cho biết hướng.',
      'ADX = làm mượt Wilder của |+DI − −DI| / (+DI + −DI) × 100',
      'Lọc tín hiệu: bỏ qua giao cắt trung bình khi ADX dưới 20.',
      'ADX là chỉ báo trễ; ADX cao có thể là cuối xu hướng.',
      'ADX trên 25: xu hướng rõ; dưới 20: đi ngang.'),
    M('ichimoku', 'technical', 'Ichimoku (mây)',
      'Hệ thống một cái nhìn gồm Tenkan (9), Kijun (26), hai biên mây Senkou A/B (dịch 26 phiên). Giá trên mây là xu hướng tăng, dưới mây là giảm, trong mây là chưa rõ.',
      'Tenkan = (cao 9 + thấp 9)/2; Kijun = (cao 26 + thấp 26)/2; Senkou A = (Tenkan + Kijun)/2',
      'Xu hướng trung hạn và vùng hỗ trợ/kháng cự động.',
      'Cần ít nhất 52 phiên; trong thị trường đi ngang mây dày cho tín hiệu nhiễu.',
      'Mây dày là vùng cản mạnh, mây mỏng dễ bị xuyên.'),
    M('supertrend-sar', 'technical', 'Supertrend và Parabolic SAR',
      'Hai đường theo xu hướng nằm dưới giá khi tăng và trên giá khi giảm; chạm đường là đảo chiều tín hiệu. Supertrend dựa trên ATR (10, 3).',
      'Supertrend = (cao+thấp)/2 ± 3 × ATR(10)',
      'Điểm cắt lỗ theo xu hướng và xác nhận hướng.',
      'Whipsaw (tín hiệu giả liên tục) khi thị trường đi ngang.',
      'Đường chuyển màu nhiều lần trong 20 phiên: thị trường đi ngang, bỏ qua.'),
    M('rsi', 'technical', 'RSI (Wilder 14)',
      'Chỉ báo động lượng 0-100 so sánh mức tăng và giảm trung bình. Trên 70 quá mua, dưới 30 quá bán; trên 50 phe mua chiếm ưu thế.',
      'RSI = 100 − 100 / (1 + RS), RS = trung bình tăng / trung bình giảm (làm mượt Wilder)',
      'Đánh giá đà và vùng quá mua/quá bán; phân kỳ RSI-giá là tín hiệu sớm.',
      'Trong xu hướng mạnh RSI có thể bám vùng quá mua/quá bán rất lâu.',
      'Trong xu hướng tăng RSI thường dao động 40-80; thủng 40 là cảnh báo.'),
    M('macd', 'technical', 'MACD (12, 26, 9)',
      'Hiệu của EMA12 và EMA26 (đường MACD), đường tín hiệu EMA9 của MACD, và histogram là chênh lệch hai đường.',
      'MACD = EMA12 − EMA26; tín hiệu = EMA9(MACD)',
      'Đà xu hướng và giao cắt tín hiệu; histogram thu hẹp báo đà yếu đi trước giao cắt.',
      'Trễ và nhiễu khi đi ngang.',
      'MACD trên 0 và trên đường tín hiệu: đà tăng đồng thuận.'),
    M('stochastic', 'technical', 'Stochastic và StochRSI',
      'Vị trí của giá đóng cửa trong biên cao-thấp N phiên; trên 80 quá mua, dưới 20 quá bán.',
      '%K = (đóng − thấp N)/(cao N − thấp N) × 100, làm mượt 3, %D = SMA3 của %K',
      'Bắt các nhịp đảo chiều ngắn hạn trong biên độ.',
      'Rất nhạy, nhiều tín hiệu giả trong xu hướng.',
      'Dùng cho thời điểm vào/ra khi xu hướng đã rõ từ các chỉ báo khác.'),
    M('cci-wr', 'technical', 'CCI và Williams %R',
      'CCI đo độ lệch của giá điển hình so với trung bình (±100 là ngưỡng mạnh); Williams %R là dạng đảo của Stochastic.',
      'CCI = (TP − SMA(TP)) / (0,015 × độ lệch tuyệt đối trung bình)',
      'Xác nhận đà và vùng cực trị.',
      'Tương quan cao với RSI/Stochastic nên không thêm nhiều thông tin độc lập.',
      'Dùng như một phiếu bầu phụ.'),
    M('bollinger', 'technical', 'Bollinger, Keltner, Donchian và nén biến động',
      'Dải Bollinger = SMA20 ± 2 độ lệch chuẩn; %B là vị trí trong dải; độ rộng dải ở phân vị thấp (nén) thường đi trước nhịp biến động mạnh (chưa biết hướng). Donchian là biên cao-thấp N phiên (bứt phá), Keltner dựa trên ATR.',
      '%B = (giá − dải dưới) / (dải trên − dải dưới)',
      'Đánh giá độ giãn, vùng bứt phá và biến động.',
      'Giá "đi dọc dải" trong xu hướng mạnh không có nghĩa là đảo chiều.',
      'Nén (độ rộng ở 10% thấp nhất 120 phiên) + bứt phá kèm khối lượng là tín hiệu đáng chú ý.'),
    M('atr-vol', 'technical', 'ATR, biến động lịch sử và sụt giảm',
      'ATR (Wilder 14) là biên dao động thật trung bình; biến động lịch sử là độ lệch chuẩn lợi suất log quy năm; sụt giảm là mức giảm từ đỉnh.',
      'TR = max(cao − thấp, |cao − đóng trước|, |thấp − đóng trước|)',
      'Đặt vùng vô hiệu kỹ thuật cách hỗ trợ một ATR; chọn quy mô vị thế theo biến động.',
      'ATR tính theo tiền, so giữa các mã cần quy ra % giá.',
      'Biến động ở phân vị cao nghĩa là cùng một vị thế rủi ro hơn.'),
    M('flow', 'technical', 'OBV, CMF, MFI, A/D, VWAP',
      'Nhóm chỉ báo dòng tiền: OBV cộng dồn khối lượng theo chiều giá; CMF và A/D đo áp lực mua/bán trong biên nến; MFI là RSI có trọng số khối lượng; VWAP 20 phiên là giá vốn bình quân người mua gần đây.',
      'CMF = Σ (số nhân dòng tiền × KL) / Σ KL; số nhân = ((đóng − thấp) − (cao − đóng)) / (cao − thấp)',
      'Xác nhận xu hướng bằng khối lượng: giá tăng cùng dòng tiền vào bền hơn giá tăng khối lượng cạn.',
      'Khối lượng không điều chỉnh khi chia tách cổ phiếu; mã kém thanh khoản cho tín hiệu nhiễu.',
      'Phân kỳ giữa giá và OBV/CMF thường báo trước đảo chiều.'),
    M('pivots-fib', 'technical', 'Điểm xoay và Fibonacci',
      'Điểm xoay (cổ điển, Fibonacci) tính từ cao-thấp-đóng của phiên/tuần/tháng trước; thoái lui 23,6/38,2/50/61,8/78,6% và mở rộng 127,2/161,8% đo từ sóng chính gần nhất trong 120 phiên.',
      'P = (C+H+L)/3; R1 = 2P − L; S1 = 2P − H',
      'Vùng giá tham khảo cho mục tiêu và điểm đảo chiều.',
      'Tính tự thực hiện (nhiều người cùng nhìn); không có cơ sở kinh tế.',
      'Mức trùng nhau giữa pivot, Fibonacci và hỗ trợ/kháng cự có độ tin cậy cao hơn mức đứng riêng.'),
    M('sr-clusters', 'technical', 'Hỗ trợ / kháng cự theo cụm',
      'Gom các đỉnh và đáy swing (5 nến mỗi bên) trong 500 phiên gần nhất cách nhau không quá 1 ATR; độ mạnh = số lần chạm có trọng số gần đây.',
      'Cụm = các điểm swing cách nhau ≤ max(ATR, 0,8% giá)',
      'Biết giá đang nằm giữa những vùng cản nào; vùng hỗ trợ nằm trong vùng tích lũy giá trị là điểm hội tụ tốt.',
      'Mức bị phá vỡ đổi vai trò (hỗ trợ thành kháng cự).',
      'Nhiều lần chạm cho biết vùng quan trọng, chưa chắc giữ được lần nữa.'),
    M('candles', 'technical', 'Mẫu nến',
      'Nhận diện trên ba nến cuối: doji, nến búa / người treo cổ, sao băng / búa ngược, nhấn chìm tăng và giảm, sao mai, sao hôm, ba chàng lính trắng, ba con quạ đen.',
      'Điều kiện theo tỷ lệ thân/bóng nến và bối cảnh xu hướng 5 phiên trước',
      'Gợi ý đảo chiều ngắn hạn khi trùng với vùng hỗ trợ/kháng cự.',
      'Độ tin cậy thống kê thấp khi đứng một mình.',
      'Mẫu nến chỉ đáng chú ý khi xuất hiện tại mức giá quan trọng và có khối lượng xác nhận.'),
    M('divergence', 'technical', 'Phân kỳ RSI - giá',
      'Giá tạo đáy thấp hơn nhưng RSI tạo đáy cao hơn (phân kỳ tăng) hoặc ngược lại ở đỉnh (phân kỳ giảm), xét trong 60 phiên.',
      'So hai đáy/đỉnh swing gần nhất của giá và RSI tại đó',
      'Tín hiệu sớm cho thấy đà đang yếu đi dù giá còn đi theo hướng cũ.',
      'Có thể kéo dài mà giá không đảo chiều.',
      'Cần xác nhận bằng phá vỡ cấu trúc giá.'),
    M('rs-line', 'technical', 'Sức mạnh tương đối so với VN-Index',
      'Tỷ lệ giá cổ phiếu trên VN-Index và lợi suất vượt trội 1/3/6/12 tháng: cổ phiếu mạnh hơn thị trường thường dẫn dắt khi thị trường đi lên.',
      'RS = giá / VN-Index; vượt trội = lợi suất cổ phiếu − lợi suất chỉ số',
      'Chọn cổ phiếu dẫn đầu và tránh mã yếu hơn thị trường.',
      'Quá khứ không bảo đảm tương lai; cổ phiếu vốn hoá lớn bị chi phối bởi chính chỉ số.',
      'RS tăng khi giá cổ phiếu giảm ít hơn thị trường cũng là tín hiệu phòng thủ.'),

    // ---------- bối cảnh thị trường ----------
    M('market-valuation', 'market', 'Mặt bằng định giá thị trường và ngành so với lịch sử',
      'P/E và P/B tổng hợp theo vốn hoá của cả thị trường và từng ngành ICB, xếp phân vị trong 5 năm: rẻ hay đắt so với CHÍNH LỊCH SỬ của nó.',
      'P/E tổng hợp = tổng vốn hoá / tổng lợi nhuận (chỉ mã có lãi, vốn hoá từ 300 tỷ)',
      'Biết bối cảnh định giá chung trước khi mua một cổ phiếu riêng lẻ.',
      'Phân ngành quá khứ theo danh sách hiện tại (thiên lệch người sống sót nhẹ); P/E tổng hợp bỏ mã lỗ nên thấp hơn P/E thật của chỉ số.',
      'Phân vị dưới 20: rẻ so với lịch sử, trên 80: đắt; rẻ có thể do lợi nhuận đang giảm.'),
    M('sector-rotation', 'market', 'Vòng quay sức mạnh ngành (JdK RS)',
      'RS-Ratio (sức mạnh so với thị trường) và RS-Momentum (đang tăng tốc hay chậm lại) chia ngành vào bốn góc: Dẫn đầu, Suy yếu, Tụt hậu, Cải thiện.',
      'RS-Ratio > 100: mạnh hơn thị trường; RS-Momentum > 100: đang tăng tốc',
      'Cổ phiếu thuộc ngành đang dẫn đầu có gió thuận.',
      'Nguồn VNDirect tính trung vị theo ngành; ngành rộng che khuất khác biệt giữa các mã.',
      'Chuyển từ Cải thiện sang Dẫn đầu là giai đoạn thường có hiệu suất tốt.'),
    M('flow-liquidity', 'market', 'Dòng tiền khối ngoại, thanh khoản và beta',
      'Mua/bán ròng khối ngoại 5 phiên so với giá trị giao dịch, thanh khoản bình quân 20 phiên, beta và room ngoại còn lại.',
      'Áp lực ngoại = ròng 5 phiên / (giá trị giao dịch TB × 5)',
      'Kiểm tra khả năng vào/ra lệnh và áp lực dòng vốn.',
      'Thanh khoản thấp làm tín hiệu kỹ thuật nhiễu và khó thoát vị thế lớn.',
      'Thanh khoản dưới 1 tỷ đồng/ngày: cân nhắc chia nhỏ lệnh hoặc bỏ qua.'),
    M('market-regime', 'market', 'Điểm bối cảnh thị trường (gió thuận / gió ngược)',
      'Tổng hợp có trọng số: xu hướng VN-Index (3), mặt bằng định giá thị trường (2), phần bù so với trái phiếu (1), định giá ngành (1), vòng quay ngành (1,5), sức mạnh tương đối của mã (1,5), dòng tiền khối ngoại (1).',
      'Điểm = Σ (điểm yếu tố × trọng số) / Σ trọng số, thang −100 đến +100',
      'Biết cổ phiếu đang bơi cùng hay ngược dòng.',
      'Yếu tố thiếu dữ liệu bị bỏ (không đoán); thị trường thuận không biến cổ phiếu xấu thành tốt.',
      'Trên +30: gió thuận; dưới −30: gió ngược; giữa: hỗn hợp.'),

    // ---------- tổng hợp ----------
    M('dcf-driver', 'intrinsic', 'DCF theo động lực (dự báo từng năm theo mảng kinh doanh)',
      'Thay vì ngoại suy tăng trưởng và biên từ lịch sử, người dùng dựng dự báo: mỗi mảng kinh doanh có doanh thu cơ sở, đường tăng trưởng và biên EBIT theo năm; cộng chi phí chung chưa phân bổ, khấu hao, capex và vốn lưu động. FCFF từng năm được chiết khấu bằng WACC, giá trị cuối kỳ theo tăng trưởng dài hạn và ROIC cuối kỳ.',
      'FCFF = EBIT × (1 − thuế) + khấu hao − capex − Δ vốn lưu động; EBIT = Σ (doanh thu mảng × biên mảng) − chi phí chung; TV = FCFF năm N+1 / (WACC − g)',
      'Khi có luận điểm cụ thể theo mảng: công suất mới, hợp đồng đã ký, mảng đang tăng tốc hoặc suy giảm; doanh nghiệp nhiều mảng có biên và tốc độ rất khác nhau.',
      'Con số chỉ tốt bằng giả định bạn nhập: dự báo chi tiết tạo cảm giác chính xác giả. Giá trị cuối kỳ thường vẫn chiếm quá nửa EV, nên WACC và tăng trưởng dài hạn vẫn là biến nhạy nhất.',
      'Kiểm tra tăng trưởng doanh thu bình quân và biên năm cuối so với lịch sử (cảnh báo khi vượt 25%/năm hoặc biên trên 40%); so với DCF tự ngoại suy để thấy luận điểm của bạn đóng góp bao nhiêu.'),
    M('normalize', 'fundamental', 'Điều chỉnh khoản bất thường (chuẩn hoá lợi nhuận)',
      'Loại các khoản lãi/lỗ không lặp lại (hoàn nhập dự phòng, lãi bán đầu tư, thanh lý tài sản) khỏi kỳ cơ sở trước khi tính P/E, EV/EBITDA, EPV và biên DCF. Khoản trong EBIT đổi EBIT, EBITDA và lợi nhuận; khoản dưới EBIT chỉ đổi lợi nhuận. Hệ thống chỉ gợi ý (thu nhập tài chính vượt xa thường lệ, lợi nhuận đổi mạnh khi doanh thu đứng yên, thuế suất bất thường), người dùng quyết định.',
      'Lợi nhuận sau thuế điều chỉnh = lợi nhuận kế toán + Σ số tiền × (1 − thuế suất)',
      'Khi lợi nhuận kỳ cơ sở chứa khoản một lần lớn làm P/E thấp hoặc cao giả tạo; đặc biệt với doanh nghiệp có thu nhập tài chính hoặc đầu tư tài chính lớn.',
      'Xác định khoản nào là bất thường cần đọc thuyết minh báo cáo: heuristic từ số liệu có thể sai. Loại quá nhiều khoản "xấu" mà giữ khoản "tốt" làm lợi nhuận bị chuẩn hoá thiên lệch.',
      'So P/E trước và sau điều chỉnh; nếu chênh lớn thì kết luận theo P/E kém tin cậy hơn kết luận theo dòng tiền.'),
    M('custom-peers', 'relative', 'Bộ mã so sánh tự chọn',
      'Thay thống kê của cả ngành ICB cấp 2 (rất rộng) bằng bội số của các đối thủ trực tiếp do người dùng chọn (từ 3 mã). Trung vị và phân vị lấy từ ảnh chụp thị trường hằng ngày, loại bội số vô lý như P/E âm.',
      'Giá ngầm định = bội số trung vị (phân vị 20/50/80) của bộ × chỉ tiêu của cổ phiếu',
      'Khi ngành ICB gộp nhiều mô hình kinh doanh khác nhau (ví dụ công nghệ gồm phần mềm, viễn thông, bán lẻ thiết bị).',
      'Bộ nhỏ cho trung vị kém ổn định và dễ bị chọn theo ý muốn kết luận; quy trình ghi nhận và cần lý do chọn. Mã thiếu báo cáo không có đủ bội số.',
      'Chọn bộ theo tiêu chí có trước (cùng mô hình, quy mô, thị trường) chứ không theo kết quả.'),
    M('process', 'synth', 'Quy trình định giá 7 bước (phân loại, dữ liệu, vai trò, giả định, đối chiếu, kiểm tra, kết luận)',
      'Thay vì chạy mọi phương pháp rồi lấy trọng số cố định, quy trình (1) phân loại mô hình kinh doanh từ số liệu, (2) kiểm cổng dữ liệu, (3) gán cho từng phương pháp một VAI TRÒ (Chính / Hỗ trợ / Đối chiếu / Tham khảo / Loại) kèm lý do, (4) liệt kê nguồn gốc giả định, (5) đối chiếu chéo các phương pháp chính, (6) chạy danh mục kiểm tra hợp lý có ngưỡng, (7) kết luận kèm hồ sơ quyết định và lý do chấp nhận.',
      'Trọng số = trọng số của vai trò (Chính 2,5; Hỗ trợ 1,2; Đối chiếu 0,5; Tham khảo và Loại 0), giảm một nửa khi phương pháp ở tình trạng "Hạn chế"',
      'Mọi lần định giá một cổ phiếu: bảo đảm phương pháp được chọn vì đúng mô hình kinh doanh, không phải vì có sẵn số.',
      'Luật phân loại và ngưỡng kiểm tra là phán đoán thực hành, không phải ước lượng thống kê; phân loại sai thì vai trò sai, nên luôn cho chọn lại. Quy trình không thay phán đoán của người định giá.',
      'Trạng thái: "Quy trình hoàn tất" khi dữ liệu đủ, các phương pháp chính đồng thuận và mọi kiểm tra đạt; "Kết luận có điều kiện" khi còn cảnh báo; "Cần xử lý" khi có mục không đạt (phải ghi lý do chấp nhận mới lưu được).'),
    M('football', 'synth', 'Biểu đồ khoảng giá và giá trị đồng thuận',
      'Mỗi phương pháp một thanh [thấp - cao] với vạch cơ sở; giá trị đồng thuận là TRUNG VỊ có trọng số của các giá trị cơ sở (bền với phương pháp lệch xa), dải là trung bình có trọng số của đầu thấp và đầu cao. Trọng số mặc định theo loại doanh nghiệp và chỉnh được.',
      'Đồng thuận = trung vị có trọng số; dải = trung bình có trọng số của thấp/cao',
      'Nhìn một lượt các phương pháp có đồng thuận hay bất đồng.',
      'Trung vị không phải sự thật: nếu cả bộ phương pháp cùng chung một giả định sai thì đồng thuận cũng sai.',
      'Thanh dài là phương pháp bất định; phương pháp lệch quá 2,5 lần hoặc dưới 0,4 lần đồng thuận bị gắn cờ.'),
    M('margin-of-safety', 'synth', 'Biên an toàn và vùng giá tham khảo',
      'Biên an toàn = 1 − giá / giá trị đồng thuận. Vùng tích lũy tham khảo = từ dưới dải hợp lý tới giá trị đồng thuận trừ biên an toàn đặt trước (mặc định 20%), điều chỉnh theo hỗ trợ kỹ thuật; vùng cân nhắc giảm tỷ trọng từ đầu cao của dải; mức vô hiệu kỹ thuật cách hỗ trợ mạnh một ATR.',
      'Vùng tích lũy cao nhất = đồng thuận × (1 − biên an toàn)',
      'Chuyển định giá thành vùng giá hành động được cho kế hoạch giao dịch.',
      'Chỉ là vùng tham khảo; không phải lệnh. Chi phí giao dịch, thuế và quy mô vị thế chưa tính.',
      'Giá trong vùng tích lũy nhưng kỹ thuật xấu: cân nhắc chia nhỏ lệnh hoặc chờ xác nhận.'),
    M('composite', 'synth', 'Kết luận kết hợp (định giá × kỹ thuật × thị trường)',
      'Điểm kết hợp = 50% định giá + 30% kỹ thuật + 20% bối cảnh thị trường (bỏ phần thiếu). Bảng kết luận cố định: rẻ + kỹ thuật tốt (hội tụ thuận lợi), rẻ + kỹ thuật xấu (nguy cơ bẫy giá trị), đắt + kỹ thuật tốt (đà chạy nhưng biên mỏng), đắt + kỹ thuật xấu (hội tụ bất lợi)...',
      'Điểm = 0,5 × định giá + 0,3 × kỹ thuật + 0,2 × thị trường',
      'Đưa ba góc nhìn (giá trị, thời điểm, bối cảnh) về một nhận định có giải thích.',
      'Không phải mô hình dự báo; trọng số là lựa chọn của người thiết kế, không tối ưu trên dữ liệu.',
      'Hãy đọc lý do và cờ đi kèm kết luận, không chỉ nhãn.'),
    M('confidence', 'synth', 'Độ tin cậy của định giá',
      'Điểm độ tin cậy giảm khi có ít phương pháp, các phương pháp bất đồng (độ phân tán), dữ liệu thiếu, hoặc điểm chất lượng báo động (Altman nguy cơ, Beneish vượt ngưỡng, dồn tích cao, Piotroski yếu).',
      'Điểm = 100 − phạt (số phương pháp, độ phân tán, cờ chất lượng); Cao ≥ 80, Vừa ≥ 55, Thấp dưới 55',
      'Biết khi nào định giá đáng tin và khi nào chỉ là một ước lượng thô.',
      'Độ tin cậy cao không có nghĩa định giá đúng, chỉ là các phương pháp nhất quán với nhau.',
      'Độ tin cậy thấp: giảm quy mô vị thế hoặc tìm thêm thông tin trước khi dựa vào con số.'),
  ];
  return { GROUPS, LIST };
})();

if (typeof module !== 'undefined' && module.exports) module.exports = VBMethods;
